[project]
name = "jack-camera"
version = "0.1.0"
description = "i be taking photos"
authors = ["Jack Arthur Harrhy <me@jackharrhy.com>"]
requires-python = ">=3.13"
dependencies = [
    "devtools>=0.12.2",
    "exif>=1.6.1",
    "pydantic>=2.12.4",
    "toml>=0.10.2",
    "typer>=0.20.0",
]
